spring.application.name=SpringApplication

spring.datasource.url=jdbc:mysql://localhost:3306/book-store-spring
spring.datasource.username=root
spring.datasource.password=0985006129ARINA@

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
